apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-ray
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: "TCP"
        targetPort: 1337
  podTemplate:
    template:
      spec:
        containers:
          - name: chal-ray
            volumeMounts:
              - name: flag-volume
              mountPath: "/chroot/flag"
        serviceAccountName: secret-readonly-sa 
        volumes:
          -name: flag-volume
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: ray-exposed-ui-secret-provider
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
    image: kind/healthcheck:ea4cb3777c14cc27f89d7c824a50e6634240b8c2294f8d7ecb9ec3d52e5fb008
  image: kind/challenge:20dee417f57d7ea09543f30ea25626a25f5476095c6011545bf43a676e2b218b
