apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-ray
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: "TCP"
        targetPort: 8265
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: kind/challenge:149a70361d09ee59c004f52dc5c09ab54fadd106d8dd7cfdd18e553232326f44
